import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { HistoryEntry, AnalysisData } from '../types';
import { saveHistoryToDB, loadHistoryFromDB, clearHistoryDB } from '../utils/idb';
import { dataUrlToBlob, createThumbnail, blobToDataUrl } from '../utils/fileUtils';
import { saveFile } from '../utils/fileSaver';

// --- App Context (Global UI State) ---

interface AppContextType {
  apiKey: string;
  setApiKey: (key: string) => void;
  toastMessage: string | null;
  setToastMessage: (message: string | null) => void;
  isLicenseModalOpen: boolean;
  setIsLicenseModalOpen: (isOpen: boolean) => void;
  installPrompt: any | null;
  handleInstallClick: () => void;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [apiKey, setApiKeyState] = useState<string>('');
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [isLicenseModalOpen, setIsLicenseModalOpen] = useState(false);
  const [installPrompt, setInstallPrompt] = useState<any>(null);

  useEffect(() => {
    const savedKey = localStorage.getItem('gemini-api-key') || '';
    setApiKeyState(savedKey);
  }, []);
  
  const setApiKey = (newKey: string) => {
    setApiKeyState(newKey);
    localStorage.setItem('gemini-api-key', newKey);
  };

  useEffect(() => {
    const handleBeforeInstallPrompt = (event: Event) => {
      event.preventDefault();
      setInstallPrompt(event);
    };
    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
    };
  }, []);
  
  const handleInstallClick = async () => {
    if (!installPrompt) return;
    await installPrompt.prompt();
    const { outcome } = await installPrompt.userChoice;
    if (outcome === 'accepted') {
      console.log('User accepted the install prompt');
    }
    setInstallPrompt(null);
  };

  const value = {
    apiKey,
    setApiKey,
    toastMessage,
    setToastMessage,
    isLicenseModalOpen,
    setIsLicenseModalOpen,
    installPrompt,
    handleInstallClick
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};

export const useApp = (): AppContextType => {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};

// --- History Context ---

interface HistoryContextType {
  history: HistoryEntry[];
  selectedHistoryId: string | null;
  isLoadingHistory: boolean;
  selectHistoryEntry: (id: string | null) => void;
  // FIX: Updated the type to not require `imageDataUrls`, as it's generated by the function.
  addHistoryEntry: (entry: Omit<HistoryEntry, 'id' | 'timestamp' | 'imageDataUrls'>) => Promise<void>;
  deleteHistoryEntry: (id: string) => void;
  clearHistory: () => Promise<void>;
  exportHistoryEntry: (id: string) => Promise<void>;
  exportAllHistory: () => Promise<void>;
  importHistory: (file: File) => Promise<void>;
}

const HistoryContext = createContext<HistoryContextType | undefined>(undefined);

const sanitizeFilename = (input: string): string => {
    return input
        .replace(/[\\/:*?"<>|]/g, '-')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, 100);
};

export const HistoryProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { setToastMessage } = useApp();
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null);
  const [isLoadingHistory, setIsLoadingHistory] = useState(true);
  const isInitialLoad = React.useRef(true);

  const migrateAndProcessHistory = useCallback(async (entries: any[]): Promise<HistoryEntry[]> => {
    if (!entries || !Array.isArray(entries)) return [];
    const processedEntries: HistoryEntry[] = [];
    for (const item of entries) {
      if (!item || !item.id || !item.result) continue;
      let entry: HistoryEntry = { ...item };
      const urlsToMigrate = entry.originalImageDataUrls || (
          Array.isArray(entry.imageDataUrls) && entry.imageDataUrls.every(url => url.length > 2048)
              ? entry.imageDataUrls
              : null
      );

      if (urlsToMigrate && !entry.imageBlobs) {
          const blobPromises = urlsToMigrate.map((url: string) => dataUrlToBlob(url));
          entry.imageBlobs = await Promise.all(blobPromises);
          delete (entry as any).originalImageDataUrls;
      }
      
      if (entry.imageBlobs && entry.imageBlobs.length > 0) {
          const dataUrlPromises = entry.imageBlobs.map(blob => blobToDataUrl(blob));
          const fullDataUrls = await Promise.all(dataUrlPromises);
          const thumbPromises = fullDataUrls.map(url => createThumbnail(url));
          entry.imageDataUrls = await Promise.all(thumbPromises);
      } else if (!entry.imageDataUrls) {
          entry.imageDataUrls = [];
      }
      processedEntries.push(entry);
    }
    return processedEntries.sort((a, b) => b.timestamp - a.timestamp);
  }, []);

  useEffect(() => {
    const initHistory = async () => {
      setIsLoadingHistory(true);
      try {
        const dbHistory = await loadHistoryFromDB();
        const processedHistory = await migrateAndProcessHistory(dbHistory);
        setHistory(processedHistory);
        const savedId = localStorage.getItem('selectedHistoryId');
        if (savedId && processedHistory.some(entry => entry.id === savedId)) {
          setSelectedHistoryId(savedId);
        }
      } catch (e) {
        console.error("Failed to load history from IndexedDB:", e);
        setToastMessage("Nie udało się załadować historii z lokalnej bazy danych.");
      } finally {
        setIsLoadingHistory(false);
        isInitialLoad.current = false;
      }
    };
    initHistory();
  }, [migrateAndProcessHistory, setToastMessage]);

  useEffect(() => {
    if (isInitialLoad.current || isLoadingHistory) return;
    saveHistoryToDB(history).catch(err => {
        console.error("Auto-save to IndexedDB failed:", err);
        setToastMessage("Automatyczny zapis historii nie powiódł się.");
    });
  }, [history, isLoadingHistory, setToastMessage]);
  
  const selectHistoryEntry = useCallback((id: string | null) => {
    setSelectedHistoryId(id);
    if (id) {
      localStorage.setItem('selectedHistoryId', id);
    } else {
      localStorage.removeItem('selectedHistoryId');
    }
  }, []);

  // FIX: Updated function signature to match the corrected type in HistoryContextType.
  const addHistoryEntry = async (entryData: Omit<HistoryEntry, 'id' | 'timestamp' | 'imageDataUrls'>) => {
    const thumbnailPromises = (entryData.imageBlobs || []).map(file => {
        const objectUrl = URL.createObjectURL(file);
        return createThumbnail(objectUrl).finally(() => URL.revokeObjectURL(objectUrl));
    });
    const thumbnailDataUrls = await Promise.all(thumbnailPromises);

    const newEntry: HistoryEntry = {
        ...entryData,
        id: new Date().toISOString() + Math.random(),
        timestamp: Date.now(),
        imageDataUrls: thumbnailDataUrls,
    };
    setHistory(prev => [newEntry, ...prev]);
    selectHistoryEntry(newEntry.id);
  };

  const deleteHistoryEntry = (id: string) => {
    const entry = history.find(e => e.id === id);
    const newHistory = history.filter(e => e.id !== id);
    setHistory(newHistory);
    if (selectedHistoryId === id) {
        selectHistoryEntry(null);
    }
    const title = entry?.result.title || entry?.result.identification?.split('\n')[0]?.replace(/\*\*/g, '') || 'Analiza bez tytułu';
    setToastMessage(`"${sanitizeFilename(title)}" usunięto z historii.`);
  };

  const clearHistory = async () => {
    setHistory([]);
    await clearHistoryDB();
    selectHistoryEntry(null);
    setToastMessage("Cała historia została pomyślnie wyczyszczona.");
  };

  const exportHistoryEntry = async (id: string) => {
    const entry = history.find(e => e.id === id);
    if (!entry) return;
    try {
        const title = entry.result.title || entry.result.identification?.split('\n')[0]?.replace(/\*\*/g, '') || 'Analiza bez tytułu';
        const fileName = `${sanitizeFilename(title)}.json`;
        const blobProvider = async (): Promise<Blob> => {
            const dataUrlPromises = entry.imageBlobs?.map(blob => blobToDataUrl(blob)) || [];
            const fullSizeDataUrls = await Promise.all(dataUrlPromises);
            const exportEntry = { ...entry, imageDataUrls: fullSizeDataUrls };
            delete (exportEntry as any).imageBlobs;
            delete (exportEntry as any).originalImageDataUrls;
            const jsonString = JSON.stringify(exportEntry, null, 2);
            return new Blob([jsonString], { type: 'application/json' });
        };
        const result = await saveFile(blobProvider, fileName);
        if (result === 'cancelled') return;
        const titleSnippet = `"${sanitizeFilename(title)}"`;
        switch (result) {
            case 'picker': setToastMessage(`Analiza ${titleSnippet} została pomyślnie zapisana.`); break;
            case 'share': case 'native': setToastMessage(`Analiza ${titleSnippet} została pomyślnie udostępniona.`); break;
            case 'legacy': setToastMessage("Funkcja 'Zapisz jako...' nie jest dostępna. Plik został pobrany automatycznie."); break;
        }
    } catch (e) {
        setToastMessage(`Błąd eksportu: ${e instanceof Error ? e.message : 'Nieznany błąd'}`);
    }
  };

  const exportAllHistory = async () => {
    if (history.length === 0) return;
    try {
        const date = new Date().toISOString().split('T')[0];
        const fileName = `numiscan-history-backup-${date}.json`;
        const blobProvider = async (): Promise<Blob> => {
            const exportHistoryPromises = history.map(async (entry) => {
                const dataUrlPromises = entry.imageBlobs?.map(blob => blobToDataUrl(blob)) || [];
                const fullSizeDataUrls = await Promise.all(dataUrlPromises);
                const exportEntry = { ...entry, imageDataUrls: fullSizeDataUrls };
                delete (exportEntry as any).imageBlobs;
                delete (exportEntry as any).originalImageDataUrls;
                return exportEntry;
            });
            const exportHistory = await Promise.all(exportHistoryPromises);
            const jsonString = JSON.stringify(exportHistory, null, 2);
            return new Blob([jsonString], { type: 'application/json' });
        };
        const result = await saveFile(blobProvider, fileName);
        if (result === 'cancelled') return;
        switch (result) {
            case 'picker': setToastMessage("Kopia zapasowa historii została pomyślnie zapisana."); break;
            case 'share': case 'native': setToastMessage("Kopia zapasowa historii została pomyślnie udostępniona."); break;
            case 'legacy': setToastMessage("Funkcja 'Zapisz jako...' nie jest dostępna. Kopia zapasowa została pobrana automatycznie."); break;
        }
    } catch (e) {
        setToastMessage(`Błąd eksportu: ${e instanceof Error ? e.message : 'Nieznany błąd'}`);
    }
  };
  
  const importHistory = async (file: File) => {
     const reader = new FileReader();
      reader.onload = async (e) => {
        try {
          const text = e.target?.result;
          if (typeof text !== 'string') throw new Error("File content is not text.");
          let data = JSON.parse(text);
          const entriesToProcess = Array.isArray(data) ? data : [data];
          const newEntries = await migrateAndProcessHistory(entriesToProcess);
          if (newEntries.length > 0) {
            setHistory(prev => {
                const existingIds = new Set(prev.map(h => h.id));
                const uniqueNewEntries = newEntries.filter(item => !existingIds.has(item.id));
                if(uniqueNewEntries.length > 0) {
                    setToastMessage(`${uniqueNewEntries.length} wpis(ów) zaimportowano pomyślnie.`);
                    return [...uniqueNewEntries, ...prev].sort((a,b) => b.timestamp - a.timestamp);
                } else {
                    setToastMessage("Nie znaleziono nowych wpisów do zaimportowania.");
                    return prev;
                }
            });
          } else {
             setToastMessage("Nie znaleziono nowych wpisów do zaimportowania.");
          }
        } catch (err) {
            setToastMessage("Błąd importu: plik JSON ma nieprawidłowy format.");
            console.error("Import failed:", err);
        }
      };
      reader.readAsText(file);
  };

  const value = {
    history,
    selectedHistoryId,
    isLoadingHistory,
    selectHistoryEntry,
    addHistoryEntry,
    deleteHistoryEntry,
    clearHistory,
    exportHistoryEntry,
    exportAllHistory,
    importHistory
  };

  return <HistoryContext.Provider value={value}>{children}</HistoryContext.Provider>;
};

export const useHistory = (): HistoryContextType => {
  const context = useContext(HistoryContext);
  if (context === undefined) {
    throw new Error('useHistory must be used within a HistoryProvider');
  }
  return context;
};
